version: '3.1'

networks:
  redv1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/29
          gateway: 172.28.1.1
 
services:
    php:
        networks:
            - redv1
        build:
            context: ./config/php
        ports:
            - 9000:9000
        volumes:
            - ./web:/srv/www/api:ro
            - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db
        links:
            - db
 
    nginx:
        networks:
            - redv1
        image: nginx:latest
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./web:/srv/www/api:ro
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./certificados:/etc/nginx/conf.d:ro
        depends_on:
            - php
 
    pma:
        networks:
            - redv1
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        ports:
            - ${IP}:8000:80
        links:
            - db:db

    db:
        networks:
            - redv1
        image: mysql:latest
        ports:
            - ${IP}:3306:3306
        command: "mysqld --init-file /data/application/init.sql"
        volumes:
            - ./data/init.sql:/data/application/init.sql
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

volumes:
    db_data: